# Generated by Django 3.0.6 on 2020-06-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200606_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pkey',
            field=models.PositiveSmallIntegerField(help_text='Unique Product Key. Current P.Key is unique', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text=' ex: $ 127.99 * Just type numbers', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Initial quantity value. Do no try to create a produt that already exists.'),
        ),
    ]
