# Generated by Django 3.0.6 on 2020-06-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200611_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.PositiveSmallIntegerField()),
                ('transition', models.IntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('user', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
            ],
        ),
    ]
