# Generated by Django 3.0.6 on 2020-06-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_histconf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histconf',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
